name: portifolio
description: collection of my works
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^4.2.2
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.4
  google_fonts: ^4.0.3
  http: ^0.13.5
  provider: ^6.0.4
  url_launcher: ^6.1.7
  flutter_localizations:
    sdk: flutter

  layout: ^1.0.3
  responsive_builder: ^0.4.1
  flutter_staggered_grid_view: ^0.4.0
  bubble_tab_indicator: "^0.1.5"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/